### ISSUE TITLE
Function "Folder -> SD" don't work

### ISSUE THREAD

**Issue by Freiwind** [SM7I/IF1bis#1]
Hi!

The path to the folder from which I am trying to copy files is truncated.
In addition, an exception error is thrown when the folder selection is closed
![Снимок1](https://user-images.githubusercontent.com/50592443/144827532-3072a344-36f9-4ff4-a3a8-86497eafb30a.JPG)
![Снимок2](https://user-images.githubusercontent.com/50592443/144827538-6e5a2524-2a03-437b-8ff1-872d25c586ef.JPG)
.

**Comment by SM7I** [comment]
Updated LDC32_GUI.exe file uploaded which has been updated to support long filenames, trunkated filenames and UTF8 filenames.
